In [1]:
import pandas as pd
import numpy as np
from processing import train_data,test_data, job_req
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

machine learn engineering 13585abc knowledge innovation youll focus research building design selfrunning artificial intelligence ai system automate predictive model responsible design create ai algorithm capable learn make prediction define machine learn ml experience qualification  bachelor master degree mention course per requirement  02 year work experience provide analytics solution commercial set technical expertise must  machine learn cluster logistic regression classification  different library scikit learn numpy panda matplotlib seaborn  deep learning framework tensorflow kera pytorch application neural network model cnn rnn gans  familiar natural language processing associate library like nltk spacy beautiful soup  pyspark hadoop big data pipeline  data science methodology exploratory data analysis feature engineering model selection deployment model scale model evaluation  deploy nlp architecture computer vision model production consider plus  transformer advance technique nl

In [2]:
print(job_req)

machine learn engineering 13585abc knowledge innovation youll focus research building design selfrunning artificial intelligence ai system automate predictive model responsible design create ai algorithm capable learn make prediction define machine learn ml experience qualification  bachelor master degree mention course per requirement  02 year work experience provide analytics solution commercial set technical expertise must  machine learn cluster logistic regression classification  different library scikit learn numpy panda matplotlib seaborn  deep learning framework tensorflow kera pytorch application neural network model cnn rnn gans  familiar natural language processing associate library like nltk spacy beautiful soup  pyspark hadoop big data pipeline  data science methodology exploratory data analysis feature engineering model selection deployment model scale model evaluation  deploy nlp architecture computer vision model production consider plus  transformer advance technique nl

In [3]:
doc_cleaned_train = pd.DataFrame(train_data,columns=['documents'])
doc_cleaned_test = pd.DataFrame(test_data,columns=['documents'])

In [4]:
print("Size: ", doc_cleaned_train.shape)
print("Size: ", doc_cleaned_test.shape)

Size:  (90, 1)
Size:  (60, 1)


In [5]:
doc_cleaned_trainX = doc_cleaned_train.append(pd.DataFrame([job_req],
                                                          columns=['documents']),ignore_index=True)

In [6]:
doc_cleaned_trainX.shape

(91, 1)

In [7]:
doc_cleaned_trainX.tail()

documents
86  shawn buffet professional profile employment h...
87  work experience hsbc bank data analyst apr 202...
88  stella thatcher executive profile work experie...
89  work experience hcl junior sdedata machine lea...
90  machine learn engineering 13585abc knowledge i...

In [8]:
bert_vec_train = sbert_model.encode(doc_cleaned_trainX['documents'])

In [9]:
bert_vec_test = sbert_model.encode(doc_cleaned_test['documents'])

In [10]:
print(type(bert_vec_train),bert_vec_train.shape)

<class 'numpy.ndarray'> (91, 768)


In [11]:
print(type(bert_vec_test),bert_vec_test.shape)

<class 'numpy.ndarray'> (60, 768)


In [12]:
print(bert_vec_train[0])

[-5.36280990e-01  6.02697611e-01  1.48722613e+00  5.63582122e-01
  4.30839419e-01 -5.25903285e-01  2.36262396e-01 -4.47528899e-01
  4.63868678e-01 -7.14169919e-01  1.55740470e-01  4.06883001e-01
  3.35456103e-01  3.37730050e-02 -9.01125491e-01  3.99030626e-01
 -2.36999914e-01 -5.44585049e-01  9.14513230e-01 -2.98524380e-01
 -3.88934046e-01 -6.61903739e-01  6.63945973e-01  3.54603380e-01
  5.44296622e-01  7.48070598e-01 -4.89221394e-01  3.87584716e-01
 -1.05052459e+00  4.70782518e-01 -1.23949718e+00  3.15410763e-01
 -8.79566073e-02 -6.50467992e-01 -3.15329522e-01  1.08649278e+00
  5.25430262e-01  5.09093463e-01  5.93532860e-01 -7.97064826e-02
 -2.38123626e-01 -2.18719408e-01  5.07087037e-02 -3.78576845e-01
 -1.64505339e+00 -4.95772064e-01 -1.31360543e+00  1.21687325e-02
  4.60826904e-01 -1.60238159e+00  4.95007075e-02  1.14434206e+00
  4.59291995e-01 -4.95415807e-01 -4.16627586e-01  7.22935140e-01
  5.45818567e-01 -1.28577077e+00 -3.43098551e-01 -4.63359207e-01
 -1.42241073e+00  6.66451

In [13]:
##Append TFidf vectorizer
tfidfvectorizer = TfidfVectorizer()
tfidf_train_vect = tfidfvectorizer.fit_transform(doc_cleaned_trainX['documents'])
tfidf_test_vec=tfidfvectorizer.transform(doc_cleaned_test['documents'])

In [14]:
type(tfidf_train_vect[0])

scipy.sparse.csr.csr_matrix

In [15]:
print(tfidf_train_vect[0].toarray().shape)

(1, 1931)


In [16]:
# Normalize bert vector
bert_vec_train_normalize = []
for bert_feature in bert_vec_train:
    bert_vec_train_normalize.append(bert_feature/np.sqrt(np.dot(bert_feature,bert_feature.T)))
    
bert_vec_test_normalize = []
for bert_feature in bert_vec_test:
    bert_vec_test_normalize.append(bert_feature/np.sqrt(np.dot(bert_feature,bert_feature.T)))

In [17]:
feature_vec_train = []
feature_vec_test = []
for bert_feature, tfidf_feature in zip(bert_vec_train_normalize,tfidf_train_vect):
    feature_vec_train.append(np.append(bert_feature,np.squeeze(tfidf_feature.toarray().T)))
    
for bert_feature, tfidf_feature in zip(bert_vec_test_normalize,tfidf_test_vec):
    feature_vec_test.append(np.append(bert_feature,np.squeeze(tfidf_feature.toarray().T)))    

print(len(feature_vec_train))
print(len(feature_vec_test))

91
60


In [18]:
ref_vec = feature_vec_train[-1]

In [19]:
import tensorflow as tf
import os

## Dataset

In [20]:
import os
os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'bertFeature.pkl',
 'feature.ipynb',
 'Model.ipynb',
 'processing.py',
 'read_pdf.py',
 'Siamese Network.ipynb',
 'static',
 'submission.csv',
 'templates',
 'tfidf.pkl',
 '__pycache__']

In [21]:
train = pd.read_csv('../dataset/train.csv')
test = pd.read_csv('../dataset/test.csv')
train.head()

CandidateID  Match Percentage
0  candidate_011             13.60
1  candidate_113             36.63
2  candidate_123             54.93
3  candidate_012             41.46
4  candidate_002             48.91

In [22]:
test.head()

CandidateID
0  candidate_014
1  candidate_098
2  candidate_075
3  candidate_016
4  candidate_131

In [23]:
train.shape

(90, 2)

In [24]:
feature_vec_train = feature_vec_train[:-1]

In [25]:
type(feature_vec_train)

list

In [26]:
len(feature_vec_train)

90

In [27]:
train['bert-tfidf'] = feature_vec_train 

In [28]:
train.head()

CandidateID  Match Percentage  \
0  candidate_011             13.60   
1  candidate_113             36.63   
2  candidate_123             54.93   
3  candidate_012             41.46   
4  candidate_002             48.91   

                                          bert-tfidf  
0  [-0.035068921744823456, 0.03941209241747856, 0...  
1  [-0.005496754311025143, 0.05249103158712387, 0...  
2  [0.006635388825088739, 0.03635752946138382, 0....  
3  [-0.03602419048547745, 0.06374359875917435, 0....  
4  [-0.04800780862569809, 0.051136553287506104, 0...

In [29]:
test['bert-tfidf'] = feature_vec_test

In [30]:
test.head()

CandidateID                                         bert-tfidf
0  candidate_014  [-0.019855467602610588, 0.05377298220992088, 0...
1  candidate_098  [-0.0040850285440683365, 0.06921227276325226, ...
2  candidate_075  [-0.051488179713487625, 0.04464828595519066, 0...
3  candidate_016  [-0.03214683011174202, 0.03543371334671974, 0....
4  candidate_131  [-0.017553701996803284, 0.05723244696855545, 0...

In [31]:
train_df = train['bert-tfidf']

In [32]:
train_out = train['Match Percentage']

In [33]:
train_df_ref = np.array([np.array(ref_vec)]*train_df.shape[0])

In [34]:
train_df_ref.shape

(90, 2699)

In [35]:
train_df_ref[0]

array([-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
        0.        ,  0.        ])

In [36]:
train_df_ref[1]

array([-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
        0.        ,  0.        ])

In [37]:
type(train_df)

pandas.core.series.Series

In [38]:
train_df = np.array(train_df)

In [39]:
train_df_ref

array([[-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ],
       [-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ],
       [-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ],
       [-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ],
       [-0.02544418,  0.06062744,  0.05386385, ...,  0.        ,
         0.        ,  0.        ]])

In [40]:
train_df

array([array([-0.03506892,  0.03941209,  0.0972539 , ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.00549675,  0.05249103,  0.10540436, ...,  0.        ,
        0.        ,  0.        ]),
       array([0.00663539, 0.03635753, 0.11206844, ..., 0.        , 0.        ,
       0.        ]),
       array([-0.03602419,  0.0637436 ,  0.07993563, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.04800781,  0.05113655,  0.08350185, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.03954075,  0.033113  ,  0.11144097, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.02977174,  0.05882068,  0.08391549, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.01046504,  0.06473319,  0.08585075, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.05801979,  0.06134104,  0.12003814, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.0245129 ,  0.05920603,  0.07965789,

In [41]:
# Dataset:: train_df, train_out, train_df_ref

In [42]:
print(type(train_df))

<class 'numpy.ndarray'>


In [43]:
print(type(train_out))

<class 'pandas.core.series.Series'>


In [44]:
print(type(train_df_ref))

<class 'numpy.ndarray'>


In [45]:
train_df[0].shape[0]

2699

In [46]:
train_df_ref.shape[1]

2699

In [105]:
df_train=pd.DataFrame(np.arange(2699).reshape(1,-1))

In [106]:
df_train.head()

0     1     2     3     4     5     6     7     8     9     ...  2689  \
0     0     1     2     3     4     5     6     7     8     9  ...  2689   

   2690  2691  2692  2693  2694  2695  2696  2697  2698  
0  2690  2691  2692  2693  2694  2695  2696  2697  2698  

[1 rows x 2699 columns]

In [107]:
for i in train_df.tolist():
    df_train = df_train.append(pd.DataFrame(i.reshape(1,-1)),ignore_index=True)
df_train.shape

(91, 2699)

In [108]:
df_train

0         1         2         3         4         5         6     \
0   0.000000  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000   
1  -0.035069  0.039412  0.097254  0.036854  0.028174 -0.034390  0.015450   
2  -0.005497  0.052491  0.105404  0.015922  0.045108 -0.026445  0.020454   
3   0.006635  0.036358  0.112068  0.038493  0.052563 -0.034066  0.033940   
4  -0.036024  0.063744  0.079936  0.014825  0.052921 -0.034398  0.010311   
..       ...       ...       ...       ...       ...       ...       ...   
86 -0.032752  0.051838  0.096068  0.025798  0.039043 -0.034132  0.023987   
87 -0.033563  0.040987  0.066883  0.027389  0.060639 -0.010191  0.000841   
88 -0.052259  0.028275  0.056550  0.016858  0.084523 -0.024778 -0.024169   
89 -0.037307  0.043390  0.085833  0.008274  0.057149 -0.014987 -0.007999   
90 -0.039394  0.047207  0.083716  0.021852  0.033309 -0.035354  0.027014   

        7         8         9     ...    2689    2690    2691    2692    2693  \
0   7.000000  8.000000  9.000000  ...  2689.0  2690.0  2691.0  2692.0  2693.0   
1  -0.029265  0.030334 -0.046702  ...     0.0     0.0     0.0     0.0     0.0   
2  -0.021225  0.029388 -0.036155  ...     0.0     0.0     0.0     0.0     0.0   
3  -0.015944  0.030683 -0.045047  ...     0.0     0.0     0.0     0.0     0.0   
4  -0.010511  0.024116 -0.036431  ...     0.0     0.0     0.0     0.0     0.0   
..       ...       ...       ...  ...     ...     ...     ...     ...     ...   
86 -0.008339  0.029089 -0.040122  ...     0.0     0.0     0.0     0.0     0.0   
87 -0.019023  0.000316 -0.015269  ...     0.0     0.0     0.0     0.0     0.0   
88  0.007519  0.013114 -0.045715  ...     0.0     0.0     0.0     0.0     0.0   
89 -0.021718  0.020348 -0.039752  ...     0.0     0.0     0.0     0.0     0.0   
90 -0.020229  0.020467 -0.033394  ...     0.0     0.0     0.0     0.0     0.0   

      2694    2695    2696    2697    2698  
0   2694.0  2695.0  2696.0  2697.0  2698.0  
1      0.0     0.0     0.0     0.0     0.0  
2      0.0     0.0     0.0     0.0     0.0  
3      0.0     0.0     0.0     0.0     0.0  
4      0.0     0.0     0.0     0.0     0.0  
..     ...     ...     ...     ...     ...  
86     0.0     0.0     0.0     0.0     0.0  
87     0.0     0.0     0.0     0.0     0.0  
88     0.0     0.0     0.0     0.0     0.0  
89     0.0     0.0     0.0     0.0     0.0  
90     0.0     0.0     0.0     0.0     0.0  

[91 rows x 2699 columns]

In [109]:
df_train=df_train.iloc[1:,:]
print(df_train)

        0         1         2         3         4         5         6     \
1  -0.035069  0.039412  0.097254  0.036854  0.028174 -0.034390  0.015450   
2  -0.005497  0.052491  0.105404  0.015922  0.045108 -0.026445  0.020454   
3   0.006635  0.036358  0.112068  0.038493  0.052563 -0.034066  0.033940   
4  -0.036024  0.063744  0.079936  0.014825  0.052921 -0.034398  0.010311   
5  -0.048008  0.051137  0.083502  0.033642  0.055629 -0.034949  0.008873   
..       ...       ...       ...       ...       ...       ...       ...   
86 -0.032752  0.051838  0.096068  0.025798  0.039043 -0.034132  0.023987   
87 -0.033563  0.040987  0.066883  0.027389  0.060639 -0.010191  0.000841   
88 -0.052259  0.028275  0.056550  0.016858  0.084523 -0.024778 -0.024169   
89 -0.037307  0.043390  0.085833  0.008274  0.057149 -0.014987 -0.007999   
90 -0.039394  0.047207  0.083716  0.021852  0.033309 -0.035354  0.027014   

        7         8         9     ...  2689  2690  2691  2692  2693  2694  \
1  -0.0292

In [111]:
df_train_ref=pd.DataFrame(np.arange(2699).reshape(1,-1))
for i in train_df_ref.tolist():
    df_train_ref = df_train_ref.append(pd.DataFrame(np.array(i).reshape(1,-1)),ignore_index=True)
df_train_ref.shape

(91, 2699)

In [112]:
df_train_ref=df_train_ref.iloc[1:,:]
df_train_ref

0         1         2         3         4         5         6     \
1  -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
2  -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
3  -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
4  -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
5  -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
..       ...       ...       ...       ...       ...       ...       ...   
86 -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
87 -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
88 -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
89 -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   
90 -0.025444  0.060627  0.053864  0.033361  0.049359 -0.024353  0.020693   

        7         8         9     ...  2689  2690  2691  2692      2693  2694  \
1  -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
2  -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
3  -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
4  -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
5  -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
..       ...       ...       ...  ...   ...   ...   ...   ...       ...   ...   
86 -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
87 -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
88 -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
89 -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   
90 -0.014916  0.017328 -0.032432  ...   0.0   0.0   0.0   0.0  0.076302   0.0   

        2695  2696  2697  2698  
1   0.107031   0.0   0.0   0.0  
2   0.107031   0.0   0.0   0.0  
3   0.107031   0.0   0.0   0.0  
4   0.107031   0.0   0.0   0.0  
5   0.107031   0.0   0.0   0.0  
..       ...   ...   ...   ...  
86  0.107031   0.0   0.0   0.0  
87  0.107031   0.0   0.0   0.0  
88  0.107031   0.0   0.0   0.0  
89  0.107031   0.0   0.0   0.0  
90  0.107031   0.0   0.0   0.0  

[90 rows x 2699 columns]

In [113]:
from keras import backend as K

def cosine_distance(vests):
    x, y = vests
    x = K.l2_normalize(x, axis=-1)
    y = K.l2_normalize(y, axis=-1)
    return -K.mean(x * y, axis=-1, keepdims=True)

def cos_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0],1)

In [140]:
input_1 = tf.keras.layers.Input(shape=(train_df[0].shape[0],))
input_2 = tf.keras.layers.Input(shape=(train_df_ref.shape[1],))

common_dense_1 = tf.keras.layers.Dense(128, activation="relu",kernel_regularizer=tf.keras.regularizers.l1(0.1))
common_dense_2 = tf.keras.layers.Dense(128, activation="relu",kernel_regularizer=tf.keras.regularizers.l2(0.01))
common_dense_3 = tf.keras.layers.Dense(64, activation="relu",kernel_regularizer=tf.keras.regularizers.l1(0.001))
common_dense_4 = tf.keras.layers.Dense(64, activation="relu",kernel_regularizer=tf.keras.regularizers.l1(0.001))
common_dense_5 = tf.keras.layers.Dense(64, activation="relu",kernel_regularizer=tf.keras.regularizers.l1(0.001))
common_dense_6 = tf.keras.layers.Dense(32, activation="relu",kernel_regularizer=tf.keras.regularizers.l1(0.001))

vector_1 = common_dense_1(input_1)
vector_1 = common_dense_2(vector_1)
vector_1 = common_dense_3(vector_1)
vector_1 = common_dense_4(vector_1)
vector_1 = common_dense_5(vector_1)
vector_1 = common_dense_6(vector_1)
vector_1 = tf.keras.layers.Flatten()(vector_1)

vector_2 = common_dense_1(input_2)
vector_2 = common_dense_2(vector_2)
vector_2 = common_dense_3(vector_2)
vector_2 = common_dense_4(vector_2)
vector_2 = common_dense_5(vector_2)
vector_2 = common_dense_6(vector_2)
vector_2 = tf.keras.layers.Flatten()(vector_2)

x3 = tf.keras.layers.Subtract()([vector_1, vector_2])
x3 = tf.keras.layers.Multiply()([x3, x3])

x1_ = tf.keras.layers.Multiply()([vector_1, vector_1])
x2_ = tf.keras.layers.Multiply()([vector_2, vector_2])
x4 = tf.keras.layers.Subtract()([x1_, x2_])

x5 = tf.keras.layers.Lambda(cosine_distance, output_shape=cos_dist_output_shape)([vector_1, vector_2])
    
conc = tf.keras.layers.Concatenate(axis=-1)([x5,x4, x3])

x = tf.keras.layers.Dense(100, activation="relu", name='conc_layer')(conc)
x = tf.keras.layers.Dropout(0.01)(x)
out = tf.keras.layers.Dense(1, activation="linear", name ='out')(x)

model = tf.keras.models.Model([input_1, input_2], out)

model.compile(loss="mean_squared_error", metrics=['mse'], optimizer=tf.keras.optimizers.RMSprop(0.01))

In [141]:
model.summary()

Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_19 (InputLayer)           [(None, 2699)]       0                                            
__________________________________________________________________________________________________
input_20 (InputLayer)           [(None, 2699)]       0                                            
__________________________________________________________________________________________________
dense_33 (Dense)                (None, 128)          345600      input_19[0][0]                   
                                                                 input_20[0][0]                   
__________________________________________________________________________________________________
dense_34 (Dense)                (None, 128)          16512       dense_33[0][0]             

In [142]:
print(type(train_out)), print(type(train_df))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


(None, None)

In [143]:
pd.Series(train_df_ref.tolist()).shape

(90,)

In [144]:
pd.Series(train_df).shape

(90,)

In [145]:
model.fit([df_train,df_train_ref],train_out,epochs = 1000,batch_size=9,validation_split=0.3)

Epoch 1/1000
7/7 [==============================] - 3s 104ms/step - loss: 2060.8892 - mse: 1664.2601 - val_loss: 2213.4802 - val_mse: 1998.9154
Epoch 2/1000
7/7 [==============================] - 0s 21ms/step - loss: 4324.1235 - mse: 4054.4233 - val_loss: 2278.5933 - val_mse: 1943.3184
Epoch 3/1000
7/7 [==============================] - 0s 21ms/step - loss: 16594.4824 - mse: 16270.7715 - val_loss: 2238.5269 - val_mse: 1929.2438
Epoch 4/1000
7/7 [==============================] - 0s 22ms/step - loss: 4605.4116 - mse: 4289.9087 - val_loss: 2192.5657 - val_mse: 1865.5123
Epoch 5/1000
7/7 [==============================] - 0s 22ms/step - loss: 1580.6106 - mse: 1266.3501 - val_loss: 577.2558 - val_mse: 268.1102
Epoch 6/1000
7/7 [==============================] - 0s 21ms/step - loss: 776.6806 - mse: 457.4899 - val_loss: 1573.7498 - val_mse: 1235.2450
Epoch 7/1000
7/7 [==============================] - 0s 23ms/step - loss: 731.4734 - mse: 405.0965 - val_loss: 547.2683 - val_mse: 236.9630
Epoc

7/7 [==============================] - 0s 29ms/step - loss: 596.3452 - mse: 447.9760 - val_loss: 303.4159 - val_mse: 152.0785
Epoch 59/1000
7/7 [==============================] - 0s 21ms/step - loss: 491.2501 - mse: 340.6851 - val_loss: 228.0526 - val_mse: 78.2294
Epoch 60/1000
7/7 [==============================] - 0s 22ms/step - loss: 275.7934 - mse: 127.2958 - val_loss: 500.6856 - val_mse: 352.6420
Epoch 61/1000
7/7 [==============================] - 0s 20ms/step - loss: 236.5732 - mse: 89.5349 - val_loss: 217.7855 - val_mse: 72.3060
Epoch 62/1000
7/7 [==============================] - 0s 22ms/step - loss: 198.6469 - mse: 53.6054 - val_loss: 225.0077 - val_mse: 79.9439
Epoch 63/1000
7/7 [==============================] - 0s 20ms/step - loss: 183.0598 - mse: 39.1343 - val_loss: 283.1419 - val_mse: 141.5749
Epoch 64/1000
7/7 [==============================] - 0s 20ms/step - loss: 173.6821 - mse: 32.7251 - val_loss: 442.2179 - val_mse: 298.7492
Epoch 65/1000
7/7 [======================

7/7 [==============================] - 0s 23ms/step - loss: 131.2141 - mse: 7.9863 - val_loss: 213.8176 - val_mse: 91.6732
Epoch 118/1000
7/7 [==============================] - 0s 22ms/step - loss: 131.4675 - mse: 9.3090 - val_loss: 222.1471 - val_mse: 99.6240
Epoch 119/1000
7/7 [==============================] - 0s 21ms/step - loss: 141.7890 - mse: 18.8717 - val_loss: 193.8597 - val_mse: 70.9270
Epoch 120/1000
7/7 [==============================] - 0s 21ms/step - loss: 134.1203 - mse: 11.7279 - val_loss: 268.2077 - val_mse: 144.4055
Epoch 121/1000
7/7 [==============================] - 0s 25ms/step - loss: 134.7584 - mse: 12.1730 - val_loss: 210.9489 - val_mse: 89.6135
Epoch 122/1000
7/7 [==============================] - 0s 22ms/step - loss: 133.7035 - mse: 11.9007 - val_loss: 202.3798 - val_mse: 79.8443
Epoch 123/1000
7/7 [==============================] - 0s 24ms/step - loss: 136.5373 - mse: 14.8060 - val_loss: 179.8715 - val_mse: 58.9263
Epoch 124/1000
7/7 [=======================

7/7 [==============================] - 0s 21ms/step - loss: 132.0304 - mse: 11.5596 - val_loss: 244.3799 - val_mse: 123.4627
Epoch 177/1000
7/7 [==============================] - 0s 22ms/step - loss: 131.7467 - mse: 11.1415 - val_loss: 285.8624 - val_mse: 165.2447
Epoch 178/1000
7/7 [==============================] - 0s 25ms/step - loss: 129.8466 - mse: 9.0018 - val_loss: 202.2527 - val_mse: 81.2068
Epoch 179/1000
7/7 [==============================] - 0s 24ms/step - loss: 135.1572 - mse: 14.3808 - val_loss: 185.8284 - val_mse: 65.0028
Epoch 180/1000
7/7 [==============================] - 0s 27ms/step - loss: 127.9790 - mse: 7.2945 - val_loss: 181.8695 - val_mse: 61.3414
Epoch 181/1000
7/7 [==============================] - 0s 23ms/step - loss: 127.9247 - mse: 7.8249 - val_loss: 206.9484 - val_mse: 86.9023
Epoch 182/1000
7/7 [==============================] - 0s 23ms/step - loss: 152.0659 - mse: 30.9059 - val_loss: 204.1360 - val_mse: 82.6598
Epoch 183/1000
7/7 [=======================

Epoch 235/1000
7/7 [==============================] - 0s 21ms/step - loss: 131.2358 - mse: 10.7512 - val_loss: 271.8674 - val_mse: 151.2943
Epoch 236/1000
7/7 [==============================] - 0s 22ms/step - loss: 140.2395 - mse: 19.1767 - val_loss: 185.8062 - val_mse: 64.2442
Epoch 237/1000
7/7 [==============================] - 0s 21ms/step - loss: 124.8635 - mse: 4.2650 - val_loss: 179.9587 - val_mse: 60.3346
Epoch 238/1000
7/7 [==============================] - 0s 20ms/step - loss: 140.6432 - mse: 20.2095 - val_loss: 194.8788 - val_mse: 73.5649
Epoch 239/1000
7/7 [==============================] - 0s 21ms/step - loss: 128.7363 - mse: 8.4221 - val_loss: 176.3336 - val_mse: 56.3078
Epoch 240/1000
7/7 [==============================] - 0s 19ms/step - loss: 132.0421 - mse: 11.5119 - val_loss: 224.3951 - val_mse: 103.4399
Epoch 241/1000
7/7 [==============================] - 0s 21ms/step - loss: 127.4149 - mse: 7.2316 - val_loss: 198.0124 - val_mse: 77.9505
Epoch 242/1000
7/7 [========

7/7 [==============================] - 0s 23ms/step - loss: 126.9099 - mse: 7.1145 - val_loss: 194.9270 - val_mse: 74.6028
Epoch 295/1000
7/7 [==============================] - 0s 22ms/step - loss: 125.5172 - mse: 5.8704 - val_loss: 183.2819 - val_mse: 64.3613
Epoch 296/1000
7/7 [==============================] - 0s 24ms/step - loss: 131.2434 - mse: 11.8721 - val_loss: 207.9167 - val_mse: 87.2116
Epoch 297/1000
7/7 [==============================] - 0s 26ms/step - loss: 147.9547 - mse: 27.1762 - val_loss: 220.2463 - val_mse: 100.1802
Epoch 298/1000
7/7 [==============================] - 0s 23ms/step - loss: 129.7176 - mse: 9.4042 - val_loss: 198.6324 - val_mse: 77.9322
Epoch 299/1000
7/7 [==============================] - 0s 24ms/step - loss: 125.5523 - mse: 5.6807 - val_loss: 239.7888 - val_mse: 120.3019
Epoch 300/1000
7/7 [==============================] - 0s 24ms/step - loss: 130.3559 - mse: 10.4716 - val_loss: 173.3573 - val_mse: 53.1846
Epoch 301/1000
7/7 [========================

7/7 [==============================] - 0s 20ms/step - loss: 126.6512 - mse: 7.2944 - val_loss: 188.8976 - val_mse: 69.9051
Epoch 354/1000
7/7 [==============================] - 0s 21ms/step - loss: 140.1463 - mse: 20.8808 - val_loss: 323.7732 - val_mse: 202.7463
Epoch 355/1000
7/7 [==============================] - 0s 20ms/step - loss: 127.4316 - mse: 7.0256 - val_loss: 194.1064 - val_mse: 74.6934
Epoch 356/1000
7/7 [==============================] - 0s 24ms/step - loss: 125.9059 - mse: 6.2509 - val_loss: 235.1410 - val_mse: 114.9700
Epoch 357/1000
7/7 [==============================] - 0s 23ms/step - loss: 124.9796 - mse: 5.4880 - val_loss: 250.7492 - val_mse: 131.9153
Epoch 358/1000
7/7 [==============================] - 0s 24ms/step - loss: 133.4724 - mse: 13.5443 - val_loss: 254.5557 - val_mse: 133.9774
Epoch 359/1000
7/7 [==============================] - 0s 21ms/step - loss: 128.4005 - mse: 8.3715 - val_loss: 191.3257 - val_mse: 72.2928
Epoch 360/1000
7/7 [=======================

7/7 [==============================] - 0s 15ms/step - loss: 135.6090 - mse: 15.9834 - val_loss: 218.0939 - val_mse: 97.6667
Epoch 413/1000
7/7 [==============================] - 0s 12ms/step - loss: 124.9639 - mse: 5.4310 - val_loss: 195.7370 - val_mse: 77.1680
Epoch 414/1000
7/7 [==============================] - 0s 19ms/step - loss: 124.9534 - mse: 6.1519 - val_loss: 168.2988 - val_mse: 48.3140
Epoch 415/1000
7/7 [==============================] - 0s 19ms/step - loss: 134.2270 - mse: 14.3735 - val_loss: 267.1100 - val_mse: 147.3877
Epoch 416/1000
7/7 [==============================] - 0s 10ms/step - loss: 125.4466 - mse: 5.8402 - val_loss: 212.3657 - val_mse: 93.1090
Epoch 417/1000
7/7 [==============================] - 0s 14ms/step - loss: 130.5433 - mse: 11.1045 - val_loss: 182.3852 - val_mse: 62.8887
Epoch 418/1000
7/7 [==============================] - 0s 12ms/step - loss: 145.5996 - mse: 25.4762 - val_loss: 203.5721 - val_mse: 82.9886
Epoch 419/1000
7/7 [========================

7/7 [==============================] - 0s 18ms/step - loss: 127.8723 - mse: 8.3734 - val_loss: 227.7512 - val_mse: 108.8724
Epoch 472/1000
7/7 [==============================] - 0s 16ms/step - loss: 145.6551 - mse: 26.0247 - val_loss: 210.7358 - val_mse: 90.8889
Epoch 473/1000
7/7 [==============================] - 0s 16ms/step - loss: 121.4131 - mse: 2.4957 - val_loss: 214.9399 - val_mse: 96.9138
Epoch 474/1000
7/7 [==============================] - 0s 18ms/step - loss: 120.1047 - mse: 1.9276 - val_loss: 238.5678 - val_mse: 120.1834
Epoch 475/1000
7/7 [==============================] - 0s 39ms/step - loss: 129.2205 - mse: 10.3867 - val_loss: 178.3523 - val_mse: 59.2260
Epoch 476/1000
7/7 [==============================] - 0s 51ms/step - loss: 126.3379 - mse: 7.1086 - val_loss: 203.8881 - val_mse: 83.9425
Epoch 477/1000
7/7 [==============================] - 0s 31ms/step - loss: 141.2177 - mse: 21.3083 - val_loss: 208.3744 - val_mse: 89.0820
Epoch 478/1000
7/7 [========================

7/7 [==============================] - 0s 16ms/step - loss: 129.3212 - mse: 9.8318 - val_loss: 204.3990 - val_mse: 84.4630
Epoch 531/1000
7/7 [==============================] - 0s 39ms/step - loss: 124.0311 - mse: 4.9168 - val_loss: 231.6828 - val_mse: 113.3119
Epoch 532/1000
7/7 [==============================] - 0s 26ms/step - loss: 120.5259 - mse: 2.1253 - val_loss: 221.2288 - val_mse: 102.6179
Epoch 533/1000
7/7 [==============================] - 0s 23ms/step - loss: 139.5656 - mse: 20.9561 - val_loss: 314.2445 - val_mse: 194.7545
Epoch 534/1000
7/7 [==============================] - 0s 18ms/step - loss: 130.9180 - mse: 11.4215 - val_loss: 200.1688 - val_mse: 80.4878
Epoch 535/1000
7/7 [==============================] - 0s 18ms/step - loss: 121.3852 - mse: 2.4157 - val_loss: 216.3291 - val_mse: 98.2524
Epoch 536/1000
7/7 [==============================] - 0s 18ms/step - loss: 125.3436 - mse: 6.8087 - val_loss: 205.8213 - val_mse: 86.4088
Epoch 537/1000
7/7 [========================

7/7 [==============================] - 0s 24ms/step - loss: 125.8098 - mse: 6.0269 - val_loss: 211.7711 - val_mse: 92.8827
Epoch 590/1000
7/7 [==============================] - 0s 21ms/step - loss: 121.8516 - mse: 2.8247 - val_loss: 223.1000 - val_mse: 103.8743
Epoch 591/1000
7/7 [==============================] - 0s 21ms/step - loss: 120.3788 - mse: 1.8665 - val_loss: 212.6775 - val_mse: 94.7692
Epoch 592/1000
7/7 [==============================] - 0s 20ms/step - loss: 120.6256 - mse: 2.3345 - val_loss: 205.9092 - val_mse: 87.0303
Epoch 593/1000
7/7 [==============================] - 0s 21ms/step - loss: 127.2970 - mse: 8.4230 - val_loss: 201.7638 - val_mse: 82.9975
Epoch 594/1000
7/7 [==============================] - 0s 21ms/step - loss: 134.0509 - mse: 14.5522 - val_loss: 223.8190 - val_mse: 103.8836
Epoch 595/1000
7/7 [==============================] - 0s 24ms/step - loss: 127.0039 - mse: 7.7267 - val_loss: 192.1446 - val_mse: 73.2300
Epoch 596/1000
7/7 [==========================

7/7 [==============================] - 0s 19ms/step - loss: 121.9086 - mse: 3.5696 - val_loss: 237.2213 - val_mse: 118.4784
Epoch 649/1000
7/7 [==============================] - 0s 18ms/step - loss: 133.4621 - mse: 14.0606 - val_loss: 223.5126 - val_mse: 103.8209
Epoch 650/1000
7/7 [==============================] - 0s 23ms/step - loss: 128.4214 - mse: 8.8064 - val_loss: 203.9145 - val_mse: 84.4875
Epoch 651/1000
7/7 [==============================] - 0s 19ms/step - loss: 127.6542 - mse: 8.5499 - val_loss: 256.1118 - val_mse: 137.5823
Epoch 652/1000
7/7 [==============================] - 0s 19ms/step - loss: 123.5519 - mse: 4.8760 - val_loss: 184.9413 - val_mse: 65.9161
Epoch 653/1000
7/7 [==============================] - 0s 19ms/step - loss: 130.9209 - mse: 11.6413 - val_loss: 226.8824 - val_mse: 107.8162
Epoch 654/1000
7/7 [==============================] - 0s 19ms/step - loss: 126.2696 - mse: 7.0174 - val_loss: 221.4946 - val_mse: 102.0204
Epoch 655/1000
7/7 [======================

7/7 [==============================] - 0s 12ms/step - loss: 123.7576 - mse: 4.5160 - val_loss: 198.0364 - val_mse: 79.4793
Epoch 708/1000
7/7 [==============================] - 0s 12ms/step - loss: 122.2530 - mse: 3.7205 - val_loss: 230.5166 - val_mse: 111.7010
Epoch 709/1000
7/7 [==============================] - 0s 11ms/step - loss: 129.2529 - mse: 10.4129 - val_loss: 168.1644 - val_mse: 48.4019
Epoch 710/1000
7/7 [==============================] - 0s 12ms/step - loss: 133.5497 - mse: 13.6930 - val_loss: 205.3588 - val_mse: 85.6839
Epoch 711/1000
7/7 [==============================] - 0s 11ms/step - loss: 122.3039 - mse: 3.4992 - val_loss: 208.9169 - val_mse: 91.0408
Epoch 712/1000
7/7 [==============================] - 0s 18ms/step - loss: 126.3836 - mse: 7.8140 - val_loss: 281.0725 - val_mse: 160.9047
Epoch 713/1000
7/7 [==============================] - 0s 14ms/step - loss: 125.7662 - mse: 6.3991 - val_loss: 209.7790 - val_mse: 91.5592
Epoch 714/1000
7/7 [=========================

7/7 [==============================] - 0s 15ms/step - loss: 133.6644 - mse: 14.3937 - val_loss: 201.3186 - val_mse: 81.3493
Epoch 767/1000
7/7 [==============================] - 0s 16ms/step - loss: 122.6261 - mse: 3.4433 - val_loss: 217.5381 - val_mse: 99.6410
Epoch 768/1000
7/7 [==============================] - 0s 15ms/step - loss: 165.2194 - mse: 46.3194 - val_loss: 194.0316 - val_mse: 73.4643
Epoch 769/1000
7/7 [==============================] - 0s 15ms/step - loss: 128.9578 - mse: 9.0116 - val_loss: 225.4976 - val_mse: 106.2124
Epoch 770/1000
7/7 [==============================] - 0s 15ms/step - loss: 123.9969 - mse: 4.6828 - val_loss: 217.7245 - val_mse: 98.2430
Epoch 771/1000
7/7 [==============================] - 0s 14ms/step - loss: 121.5941 - mse: 2.7673 - val_loss: 212.8635 - val_mse: 94.8238
Epoch 772/1000
7/7 [==============================] - 0s 15ms/step - loss: 120.7863 - mse: 2.6294 - val_loss: 211.0515 - val_mse: 92.3300
Epoch 773/1000
7/7 [==========================

7/7 [==============================] - 0s 18ms/step - loss: 143.1073 - mse: 24.3070 - val_loss: 184.5058 - val_mse: 64.9766
Epoch 826/1000
7/7 [==============================] - 0s 15ms/step - loss: 125.9723 - mse: 6.5814 - val_loss: 225.6131 - val_mse: 106.3552
Epoch 827/1000
7/7 [==============================] - 0s 15ms/step - loss: 121.1253 - mse: 2.5544 - val_loss: 204.6986 - val_mse: 86.7794
Epoch 828/1000
7/7 [==============================] - 0s 16ms/step - loss: 124.2718 - mse: 5.7262 - val_loss: 290.3420 - val_mse: 170.6928
Epoch 829/1000
7/7 [==============================] - 0s 14ms/step - loss: 124.3642 - mse: 5.5753 - val_loss: 208.5829 - val_mse: 90.9465
Epoch 830/1000
7/7 [==============================] - 0s 15ms/step - loss: 135.3335 - mse: 16.6314 - val_loss: 313.5555 - val_mse: 193.1920
Epoch 831/1000
7/7 [==============================] - 0s 15ms/step - loss: 126.2160 - mse: 6.5275 - val_loss: 234.4801 - val_mse: 115.6927
Epoch 832/1000
7/7 [=======================

7/7 [==============================] - 0s 15ms/step - loss: 120.9889 - mse: 2.8101 - val_loss: 257.3690 - val_mse: 138.6370
Epoch 885/1000
7/7 [==============================] - 0s 21ms/step - loss: 125.8552 - mse: 6.9572 - val_loss: 225.5267 - val_mse: 107.0867
Epoch 886/1000
7/7 [==============================] - 0s 19ms/step - loss: 122.6329 - mse: 4.3619 - val_loss: 248.5271 - val_mse: 129.7589
Epoch 887/1000
7/7 [==============================] - 0s 19ms/step - loss: 139.3323 - mse: 20.1189 - val_loss: 199.4367 - val_mse: 79.5961
Epoch 888/1000
7/7 [==============================] - ETA: 0s - loss: 125.5298 - mse: 5.964 - 0s 18ms/step - loss: 125.3497 - mse: 5.9343 - val_loss: 221.2742 - val_mse: 102.4645
Epoch 889/1000
7/7 [==============================] - 0s 15ms/step - loss: 125.7285 - mse: 7.1331 - val_loss: 224.3788 - val_mse: 105.9918
Epoch 890/1000
7/7 [==============================] - 0s 16ms/step - loss: 122.5744 - mse: 4.0330 - val_loss: 233.9218 - val_mse: 114.9094
Ep

Epoch 943/1000
7/7 [==============================] - 0s 16ms/step - loss: 133.6832 - mse: 14.1054 - val_loss: 265.5468 - val_mse: 146.2721
Epoch 944/1000
7/7 [==============================] - 0s 21ms/step - loss: 123.1302 - mse: 4.0486 - val_loss: 214.4320 - val_mse: 95.8399
Epoch 945/1000
7/7 [==============================] - 0s 22ms/step - loss: 120.1520 - mse: 2.1845 - val_loss: 182.1214 - val_mse: 64.3704
Epoch 946/1000
7/7 [==============================] - 0s 18ms/step - loss: 133.8449 - mse: 14.9583 - val_loss: 227.1311 - val_mse: 107.6033
Epoch 947/1000
7/7 [==============================] - 0s 20ms/step - loss: 122.0760 - mse: 3.4499 - val_loss: 235.9640 - val_mse: 118.1345
Epoch 948/1000
7/7 [==============================] - 0s 18ms/step - loss: 122.0266 - mse: 3.8642 - val_loss: 185.5580 - val_mse: 66.2933
Epoch 949/1000
7/7 [==============================] - 0s 18ms/step - loss: 135.5291 - mse: 15.7161 - val_loss: 226.3821 - val_mse: 106.7118
Epoch 950/1000
7/7 [=======

In [146]:
import pickle

In [147]:
pickle.dump(model,open('model.pkl','wb'))

AttributeError: Can't pickle local object 'Layer.add_loss.<locals>._tag_callable'

In [148]:
model.save("my_model")

INFO:tensorflow:Assets written to: my_model\assets


C:\Users\anupa\anaconda3\lib\site-packages\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


In [149]:
test.head()

CandidateID                                         bert-tfidf
0  candidate_014  [-0.019855467602610588, 0.05377298220992088, 0...
1  candidate_098  [-0.0040850285440683365, 0.06921227276325226, ...
2  candidate_075  [-0.051488179713487625, 0.04464828595519066, 0...
3  candidate_016  [-0.03214683011174202, 0.03543371334671974, 0....
4  candidate_131  [-0.017553701996803284, 0.05723244696855545, 0...

In [150]:
My_data = test['bert-tfidf']

In [151]:
type(My_data)

pandas.core.series.Series

In [153]:
My_data = np.array(My_data)

In [154]:
My_data

array([array([-0.01985547,  0.05377298,  0.12351051, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.00408503,  0.06921227,  0.10084466, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.05148818,  0.04464829,  0.08095501, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.03214683,  0.03543371,  0.09734838, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.0175537 ,  0.05723245,  0.10827108, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.02833689,  0.04094543,  0.10830949, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.03630507,  0.03700452,  0.11058752, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.02589451,  0.03874171,  0.09175021, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.02577159,  0.02714813,  0.11174339, ...,  0.        ,
        0.        ,  0.        ]),
       array([-0.04506445,  0.05341544,  0.060

In [155]:
test_df  = pd.DataFrame(np.arange(2699).reshape(1,-1))

In [156]:
for i in My_data.tolist():
    test_df = test_df.append(pd.DataFrame(i.reshape(1,-1)),ignore_index=True)
My_data.shape

(60,)

In [158]:
test_df.shape

(61, 2699)

In [159]:
test_df = test_df.iloc[1:,:]

In [160]:
test_df.shape

(60, 2699)

In [163]:
test_label = model.predict([test_df,df_train_ref.iloc[:60,:]])

In [167]:
type(test_label)

numpy.ndarray

In [170]:
test['Match Percentage'] = test_label
test = test.drop('bert-tfidf',axis=1)

In [171]:
test.head()

CandidateID  Match Percentage
0  candidate_014         27.903101
1  candidate_098         42.471138
2  candidate_075         20.565212
3  candidate_016         42.676170
4  candidate_131         28.673000

In [172]:
test.to_csv('submission.csv',index=False)